on:
  push:
    branches:
      - master

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploying
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Getting the latest code
        uses: actions/checkout@v3
      - name: 📂 Sync
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.tomandsonsltd.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /
          
    # - uses: actions/checkout@v4
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    # - name: Run Tests
    #   run: |
    #     python manage.py test
    
